_wandb:
    value:
        cli_version: 0.25.1
        e:
            13weq8llnr86jd049fs5fu4jn6dt1aaq:
                codePath: /root/lab/project/meteorite.ipynb
                codePathLocal: meteorite.ipynb
                cpu_count: 64
                cpu_count_logical: 128
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "7615235203072"
                        used: "156686499840"
                email: jacob.jingming.li@gmail.com
                executable: /opt/venv/bin/python
                gpu: NVIDIA A30
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 3584
                      memoryTotal: "25769803776"
                      name: NVIDIA A30
                      uuid: GPU-64287af5-46dc-37c4-8b4b-cca962f38feb
                host: 1f12722bd38d
                memory:
                    total: "1081594793984"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.39
                program: /root/lab/project/meteorite.ipynb
                python: CPython 3.12.3
                root: /root/lab/project
                startedAt: "2026-03-25T09:51:45.108617Z"
                writerId: 13weq8llnr86jd049fs5fu4jn6dt1aaq
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
            "2":
                - 1
                - 41
                - 49
                - 63
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.3
            "5": 0.25.1
            "8":
                - 1
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 32
image_size:
    value: 224
learning_rate:
    value: 0.0003
model_name:
    value: efficientnetv2_s
num_classes:
    value: 2
num_epochs:
    value: 10
num_workers:
    value: 2
output_dir:
    value: ./logs
project_name:
    value: sta326-meteorite
run_name:
    value: efficientnetv2_s-baseline
val_ratio:
    value: 0.2
weight_decay:
    value: 0.0001
